# Generated by Django 6.0.3 on 2026-03-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dpi',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='numero_cuenta',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
